fixing Makefiles; fixing tlast in wrapper

diff --git a/LIB/HW/hls/mpi_wrapperv1/Makefile b/LIB/HW/hls/mpi_wrapperv1/Makefile
--- a/LIB/HW/hls/mpi_wrapperv1/Makefile
+++ b/LIB/HW/hls/mpi_wrapperv1/Makefile
@@ -2,12 +2,21 @@
 #ipName = jacobi2dv0
 appName =mpi_wrapper
 ipName =${appName}v1
+DIM=16
 
 #DEPS := $(shell find ./src/ -type f)
 DEPS := $(shell find ./src/ )
+IP_GUARD=$(usedRoleDir).ip_guard
 
-.PHONY: all csim cosim cosim_view
-all: ${ipName}_prj/solution1/impl/ip
+.PHONY: all csim cosim cosim_view assert_env
+all: assert_env ${ipName}_prj/solution1/impl/ip
+
+# assert ENVIRONMENT
+assert_env:
+ifndef usedRoleDir
+	@echo "ERROR: usedRoleDir MUST BE DEFINED as environment variable!" 
+	@exit 1
+endif
 
 ${ipName}_prj/solution1/impl/ip: $(DEPS)
 	@#rm -rf $@
@@ -15,13 +24,14 @@ ${ipName}_prj/solution1/impl/ip: $(DEPS)
 	export hlsSim=0; export hlsCoSim=0; vivado_hls -f run_hls.tcl
 	@#touch ${ipName}_prj
 	@touch $@
-	@touch ../../.ip_guard
+	touch $(IP_GUARD)
 
-csim: 
+csim:
+	@/bin/echo -e "---------------\n\tThis simulation works only with *one* iteration with DIM $(DIM)!\n\t(so it expects one recv and one send from the app)\n---------------\n"
 	export hlsSim=1; export hlsCoSim=0; vivado_hls -f run_hls.tcl
 
 
-cosim: 
+cosim:
 	export hlsSim=0; export hlsCoSim=1; vivado_hls -f run_hls.tcl
 
 cosim_view:
